ELGamalre
decipherhub/Cryptography pull request #75
Opened 2024-11-04 07:15 UTC by abell1689neo

# What does this PR do?
 
ELGamal에 대한 설명이 간략한 것 같아 좀 더 자세하게 내용을 추가했고, 그림을 통해 이해가 편하도록 바꾸어보았습니다. 

## Before reviewing
- [ ] Check for missing / redundant content
- [ ] Grammar Check
- [ ] Check if the content is accurate

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@hwamzzx

2024-11-04 08:49 UTC, healthykim requested changes
LGTM! Just change the name of the image file to "ElGamal(1).png"

2024-11-05 06:34 UTC, healthykim approved these changes

2024-11-15 04:19 UTC, yijun-lee commented
@hwamzzx

2024-11-16 05:45 UTC, healthykim approved these changes

2024-12-06 15:20 UTC, merged